# Header
# navname: HTTISHERE's Blog
navname: ğ‘¯ğ‘»ğ‘»ğ‘°ğ‘ºğ‘¯ğ‘¬ğ‘¹'ğ‘©ğ’ğ’ğ’ˆ
# navlogo: 

# navigatior items
nav:
  Posts: /archives
  Categories: /category
  Tags: /tag
  Schedules: /reading
  About: /about

# favicon
favicon: /favicon.ico

# Profile
nickname: HTTISHERE

### this variable is MarkDown form.
description: Life was like a box of chocolates, you never know what youâ€™re gonna get.<br>ç”Ÿå‘½å°±åƒä¸€ç›’å·§å…‹åŠ›ï¼Œç»“æœå¾€å¾€å‡ºäººæ„æ–™ã€‚<br>I donâ€™t know if we each have a destiny, or if weâ€™re all just floating around accidentallyâ€•like on a breeze.<br>æˆ‘ä¸æ‡‚æˆ‘ä»¬æ˜¯å¦æœ‰ç€å„è‡ªçš„å‘½è¿ï¼Œè¿˜æ˜¯åªæ˜¯åˆ°å¤„éšé£é£˜è¡ã€‚
avatar: /image/avatar.png

# main menu navigation
## links key words should not be changed.
## Complete url after key words.
## Unused key can be commented out.
links:
  Blog: /archives
  # Category:
  # Tags: HTTISHERE
  # Link:
  # Resume:
  # Publish:
  # Trophy:
  # Gallery:
  # RSS:
  # AliPay:
  ZhiHu: https://www.zhihu.com/people/a-wang-16
  # LinkedIn:
  # FaceBook:
  # Twitter:
  # Skype:
  # CodeSandBox:
  # CodePen:
  # Sketch:
  # Gitlab:
  # Dribbble:
  # Instagram:
  # Reddit:
  # YouTube:
  # QQ:
  Weibo: https://m.weibo.cn/login?backURL=https%3A%2F%2Fm.weibo.cn%2Fprofile%2F1840417414
  # WeChat:
  Github: https://github.com/httIsHere
  Notion: https://descriptive-impulse-a6e.notion.site/Hello-here-is-Tina-b10f03f2226e449887ad86b097e67e78

# how links show: you have 2 choice--text or icon.
links_text_enable: false
links_icon_enable: true

# Post page
## Post_meta
post_meta_enable: true

post_author_enable: true
post_date_enable: true
post_category_enable: true
## Post copyright
post_copyright_enable: true

post_copyright_author_enable: true
post_copyright_permalink_enable: true
post_copyright_license_enable: true
post_copyright_license_text: Copyright (c) 2021 <a href="http://creativecommons.org/licenses/by-nc/4.0/">CC-BY-NC-4.0</a> LICENSE
post_copyright_slogan_enable: true
post_copyright_slogan_text: Good Good Study, Day Day Up.
## toc
post_toc_enable: true

# Page
page_title_enable: true

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY/MM/DD
time_format: H:mm:ss

# stylesheets loaded in the <head>
stylesheets:
  - /css/style.css

# scripts loaded in the end of the body
scripts:
  - /js/script.js
  - /js/tocbot.min.js
    # tscanlin/tocbot: Build a table of contents from headings in an HTML document.
    # https://github.com/tscanlin/tocbot


# plugin functions
## Mathjax: Math Formula Support
## https://www.mathjax.org
mathjax:
  enable: true
  import: demand # global or demand
  ## global: all pages will load mathjax,this will degrade performance and some grammers may be parsed wrong.
  ## demand: Recommend option,if your post need fomula, you can declare 'mathjax: true' in Front-matter

gitalk:
  enable: true
  owner: httIsHere
  admin: httIsHere
  repo: httIsHere.github.io
  ClientID: c61a26564784a9cb16f3
  ClientSecret: 25a391b4405c726bfa417a4d09a8a9d46fd41e12
  labels: 'gitalk'
  distractionFreeMode: true

leancloud_visitors:
  enable: true
  app_id: 1BHDvzMyiyWmu3v3vBaR2dek-gzGzoHsz
  app_key: MaYtrzsGSwqpImuLueThWKFE

valine:
 appid:  1BHDvzMyiyWmu3v3vBaR2dek-gzGzoHsz
 appkey:  MaYtrzsGSwqpImuLueThWKFE
 verify: true #éªŒè¯ç 
 notify: true #è¯„è®ºå›å¤æé†’
 placeholder: è¿™é‡Œç•™è¨€ã€‚ã€‚ #è¯„è®ºæ¡†å ä½ç¬¦
 visitor: true	#é˜…è¯»é‡ç»Ÿè®¡

post_wordcount:
  item_text: true
  wordcount: true         # å•ç¯‡ å­—æ•°ç»Ÿè®¡
  min2read: true          # å•ç¯‡ é˜…è¯»æ—¶é•¿
  totalcount: false       # ç½‘ç«™ å­—æ•°ç»Ÿè®¡

post_wordcount_enable: true
post_min2read_enable: true

auto_excerpt:
  enable: true
  length: 150